In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
#everything we will import to use later
import os
import numpy as np
import pandas as pd
from datetime import datetime, date, timedelta
from matplotlib import pyplot as plt
from functions import add_max_rainfall, OrdinalToDatetime
import tqdm
from tqdm.notebook import tqdm_notebook

2023-04-24 13:26:27.666302: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [3]:
# airport_df = pd.read_csv('./sitka_data/Airport_new/cleaned_data/airport_cleaned_3_hour_wind.csv')#, index_col='Date_Time')
# usgs_df = pd.read_csv('./sitka_data/USGS_new/cleaned_data/usgs_cleaned_3_hour_dt.csv')#, index_col='Date_Time')
# airport_df["Date_Time"] = pd.to_datetime(airport_df["Date_Time"])
# usgs_df["Date_Time"] = pd.to_datetime(usgs_df["Date_Time"])
# usgs_df = usgs_df[usgs_df["Date_Time"]>="2020-06-09 21:00:00"]
# combined_df = airport_df.merge(usgs_df, on="Date_Time", how="left")
# combined_df.set_index("Date_Time", inplace=True, drop=True)

In [3]:
#combined_df

In [7]:
# combined_df.to_csv('./sitka_data/combined_3_hour_wind.csv', columns=["wind_speed_meter_sec", 
#                                                                     "wind_direction_x", "wind_direction_y", 
#                                                                     "precip_accum_one_hour_mm", "Sitka_ec5_vwc_sp2_40cm_mean", 
#                                                                     "Sitka_ec5_vwc_sp2_20cm_mean", "Sitka_waterPressure_psig_sp2_60cm_mean", 
#                                                                     "Sitka_ec5_vwc_sp2_40cm_max", "Sitka_ec5_vwc_sp2_20cm_max",	
#                                                                     "Sitka_waterPressure_psig_sp2_60cm_max", "Sitka_ec5_vwc_sp2_40cm_dt", "Sitka_ec5_vwc_sp2_20cm_dt", 
#                                                                     "Sitka_waterPressure_psig_sp2_60cm_dt"], date_format='%Y-%m-%d %H:%M:%S')

In [4]:
ocr = pd.read_csv('./sitka_data/combined_3_hour_wind.csv', index_col='Date_Time')#,sep='\t')
#ocr = pd.read_csv('./SP1.csv')

# ocr["Date_Time"] = ocr["timestamp_utc"]
# for ii in range(len(ocr["timestamp_utc"])):
#     ocr["Date_Time"][ii] = OrdinalToDatetime(ocr["timestamp_utc"][ii])

#ocr.index = pd.to_datetime(ocr["Date_Time"])
#ocr.drop(["timestamp_utc"], axis=1, inplace=True)

pp_cols = [v for v in ocr.columns if "Pressure_" in v]  # allows any pp depths, as the depth varies from pit to pit
VWC_cols = [v for v in ocr.columns if "VWC_" in v]  # allows any water content depths, as the depth varies from pit to pit
ocr[pp_cols] = ocr[pp_cols].mask(ocr[pp_cols] < -14) #mask pp smaller than -14, we're interested in larger pp

# add in forecasted rainfall
for i in tqdm_notebook(range(3,75,3)):
    ocr = add_max_rainfall(ocr, i, 0, noise=False)
    
#df.sort_index(axis=1, inplace=True) 
    
cols_at_end = VWC_cols + pp_cols
ocr = ocr[[c for c in ocr if c not in cols_at_end] + [c for c in cols_at_end if c in ocr]]

ocr.to_csv('./sitka_data/processed_for_training_3_hour_72.csv')

  0%|          | 0/24 [00:00<?, ?it/s]

In [5]:
ocr

,precip_accum_one_hour_mm,wind_speed_meter_sec,wind_direction_x,wind_direction_y,Sitka_ec5_vwc_sp2_40cm_mean,Sitka_ec5_vwc_sp2_20cm_mean,Sitka_ec5_vwc_sp2_40cm_max,Sitka_ec5_vwc_sp2_20cm_max,Sitka_ec5_vwc_sp2_40cm_dt,Sitka_ec5_vwc_sp2_20cm_dt,...,63hr_max_rfall,66hr_total_rfall,66hr_max_rfall,69hr_total_rfall,69hr_max_rfall,72hr_total_rfall,72hr_max_rfall,Sitka_waterPressure_psig_sp2_60cm_mean,Sitka_waterPressure_psig_sp2_60cm_max,Sitka_waterPressure_psig_sp2_60cm_dt
Date_Time,,,,,,,,,,,,,,,,,,,,,
11/6/02 6:00,0.000,6.690000,0.984808,-0.173648,NaN,NaN,NaN,NaN,NaN,NaN,...,6.604,30.480,6.604,34.798,6.604,35.306,6.604,NaN,NaN,NaN
11/6/02 9:00,0.000,9.770000,0.939693,-0.342020,NaN,NaN,NaN,NaN,NaN,NaN,...,6.604,32.004,6.604,35.052,6.604,35.306,6.604,NaN,NaN,NaN
11/6/02 12:00,3.048,8.860000,0.672951,-0.652663,NaN,NaN,NaN,NaN,NaN,NaN,...,6.604,33.274,6.604,35.306,6.604,36.830,6.604,NaN,NaN,NaN
11/6/02 15:00,1.778,4.743333,0.564370,-0.748878,NaN,NaN,NaN,NaN,NaN,NaN,...,6.604,31.750,6.604,32.258,6.604,35.306,6.604,NaN,NaN,NaN
11/6/02 18:00,0.508,2.515556,0.637579,0.142455,NaN,NaN,NaN,NaN,NaN,NaN,...,6.604,30.226,6.604,30.480,6.604,34.290,6.604,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3/21/23 9:00,0.000,NaN,NaN,NaN,0.209750,0.214944,0.210,0.216,0.0006,0.0004,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.279200,0.285976,0.000119
3/21/23 12:00,0.000,NaN,NaN,NaN,0.208833,0.214833,0.209,0.215,0.0004,0.0004,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.264137,0.271667,0.000065
3/21/23 15:00,0.000,NaN,NaN,NaN,0.208556,0.214806,0.209,0.215,0.0006,0.0006,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.254217,0.257418,0.000059
3/21/23 18:00,0.000,NaN,NaN,NaN,0.207972,0.214917,0.209,0.216,0.0004,0.0006,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.247625,0.251391,0.000216
3/21/23 21:00,0.000,NaN,NaN,NaN,0.208042,0.215792,0.209,0.216,0.0004,0.0006,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.239277,0.242719,0.000246